from pathlib import Path
import hashlib,json,xml.etree.ElementTree as ET,datetime
R=Path('<REPO>');B=R/'artifacts/verification/VPKB-000-projection-contracts';OUT=B/'assessment-history';TMP=Path('<TMP>');A=TMP/'vph-acceptance';H=lambda b:hashlib.sha256(b).hexdigest();entries={};OUT.mkdir(exist_ok=True)
def norm(s):return s.replace(str(R),'<REPO>').replace('<USER_HOME>','<USER_HOME>').replace('<TMP>','<TMP>')
def copy(src,dst):
 raw=src.read_bytes();b=norm(raw.decode()).encode()
 if src.suffix in ('.log','.stdout','.stderr'):b=('\n'.join(line.rstrip(' \t') for line in b.decode().splitlines()).rstrip('\n')+'\n').encode() if b else b
 dst.parent.mkdir(parents=True,exist_ok=True);dst.write_bytes(b);entries[str(dst.relative_to(OUT))]={'original_path':norm(str(src)),'raw_sha256':H(raw),'raw_bytes':len(raw),'archived_sha256':H(b),'archived_bytes':len(b),'transform':'byte-exact' if raw==b else 'path tokens; plain logs also remove per-line trailing spaces/tabs and excess blank EOF'}
def write(path,obj):path.write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n')
for name in ['source-files.json','python312-source-after.json','python313-source-after.json','python312-result.json','python313-result.json','python312.log','python313.log','wheel-result.json','wheel-build.log','wheel-install.log','wheel-smoke.log','wheel-smoke.py']:copy(A/name,OUT/'local'/name)
for name in ['vph-run-suites.py','vph-run-wheel.py','vph-archive-evidence.py']:copy(TMP/name,OUT/'runners'/name)
copy(TMP/'vph-architect-local-review.json',OUT/'local/architect-review.json')
for name in ['vph-steward-build-vectors.py','vph-steward-vectors.json','vph-steward-runtime-cases.py','vph-steward-review-outline.md','vph-steward-preparation.json','vph-steward-review-candidate.py','vph-steward-review-candidate.json','vph-steward-review-candidate.log','vph-steward-review-final.json','vph-steward-focused.log']:copy(TMP/name,OUT/'independent'/name)
for name in ['vph-freeze.json','vpkb-assessment-history-spec-builder-review.md','vpkb-assessment-history-spec-steward-review.json','vpkb-assessment-history-spec-probes.py','vpkb-assessment-history-spec-probes.json']:copy(TMP/name,OUT/'spec-review'/name)
for name in ['vph-candidate.json','vph-builder-generate.py']:copy(TMP/name,OUT/'builder'/name)
copy(TMP/'vph-builder-tests/target4.log',OUT/'builder/target4.log')
junit={}
for label,p in [('python312',A/'python312.xml'),('python313',A/'python313.xml'),('independent-focused',TMP/'vph-steward-focused.xml'),('builder-targeted',TMP/'vph-builder-tests/target4.xml')]:
 root=ET.parse(p).getroot();s=list(root) if root.tag=='testsuites' else [root];junit[label]={'original_path':norm(str(p)),'raw_sha256':H(p.read_bytes()),'raw_bytes':p.stat().st_size,'counts':{k:sum(int(x.get(k,0)) for x in s) for k in ['tests','failures','errors','skipped']},'suite_seconds':sum(float(x.get('time',0)) for x in s),'xml_archived':False}
write(OUT/'junit-summary.json',junit)
source=json.loads((A/'source-files.json').read_text());assert source['file_count']==292 and all(H((R/n).read_bytes())==s for n,s in source['files'].items())
for label in ['312','313']:
 result=json.loads((A/('python'+label+'-result.json')).read_text());assert result['exit_code']==0 and result['counts']=={'tests':1596,'failures':0,'errors':0,'skipped':0};assert json.loads((A/('python'+label+'-source-after.json')).read_text())['files']==source['files']
w=json.loads((A/'wheel-result.json').read_text());assert all(x['exit_code']==0 for x in w['commands']);review=json.loads((TMP/'vph-steward-review-final.json').read_text());assert review['independent_probes']['passed']==85
write(OUT/'local-results.json',{'observed_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline_head':'3e2bebb1d50928a7af95e07b4868bdbe8113cd0b','source_kind':'working-tree candidate; future commit and CI are not self-referenced','contract_revision':1,'contract_sha256':'ff7e7830d9931c52c447a2a95818dca091cb6d5bc97184d1be1103072ecf44cb','source_count':292,'source_snapshot_sha256':source['snapshot_sha256'],'source_before_after_equal':True,'local_status':'passed','full_suites':{k:junit[k] for k in ['python312','python313']},'independent':{'positive_vectors':29,'negative_vectors':38,'probes_passed':85,'probes_failed':0,'focused_tests':junit['independent-focused']['counts']},'builder_targeted_tests':junit['builder-targeted']['counts'],'wheel':{'status':'passed','sha256':w['wheel_sha256'],'schema_count':18,'commands_exit_codes':[x['exit_code'] for x in w['commands']],'old_smoke_and_29positive_38negative':'passed','binary_archived':False},'architect_local_review_raw_sha256':H((TMP/'vph-architect-local-review.json').read_bytes()),'ci_status':'not yet observed for new candidate; old locator CI is historical only','limits':['Supplied-history consistency only: no complete Vault enumeration, owner/source/artifact existence, human authorization, receipt/rollback integrity, or core replacement transaction co-publication.','Synthetic graph-only cycle tests are not self-consistent event-hash cycles.','Pre/post snapshots do not establish continuous filesystem monitoring.','Old API/schema/identity/locator/runtime behavior is unchanged; full input/SQLite/generation and VPKB-000 remain open.']})
external=[TMP/'vpl-acceptance/wheel-smoke.py',TMP/'vpl-steward-vectors.json'];fixture=TMP/'vpr-root-target2/test_pinned_public_rebuild_cjk0';external+=sorted((fixture/'round-1/.vault-meta/chunks').glob('*/*.json'))+[fixture/'round-1/index.json',fixture/'round-2/index.json']
write(OUT/'external-inputs.json',{'purpose':'Historical inputs actually read by inherited installed-wheel smoke; hash references only, no old directories recopied. Repository fixtures are covered by source-files.json. Temporary scripts retain path tokens; restoring referenced files is a replay prerequisite.','files':{norm(str(p)):{'raw_sha256':H(p.read_bytes()),'bytes':p.stat().st_size} for p in external},'prior_locator_archive':'../ledger-locator/local/wheel-smoke.py and ../ledger-locator/independent/vpl-steward-vectors.json preserve normalized/exact copies with original digests in their manifest.'})
write(OUT/'archive-manifest.json',{'normalization':'Replace repository root with <REPO>, remaining user home with <USER_HOME>, <TMP> with <TMP>. Plain logs additionally remove trailing spaces/tabs and excess blank EOF. Internal JSON numbers/wire text and all stated original digest fields are unchanged. JUnit XML is omitted, retaining only raw digest/counts. Historical scripts are reviewable normalized sources, not replayed archive bytes.','files':entries})
D=B/'dependency-source';src=TMP/'vpkb-dependency-architect-check.py';raw=src.read_bytes();archived=norm(raw.decode()).encode();(D/'architect-check.py').write_bytes(archived);original=TMP/'vpkb-dependency-architect-review.json';target=D/'architect-review.json';assert target.read_bytes()==original.read_bytes()
write(D/'architect-archive.json',{'scope':'Later independent Architect check; append-only index, previous source observation/archive manifest/pinned dependency status unchanged.','script':{'original_path':'<TMP>/vpkb-dependency-architect-check.py','raw_sha256':H(raw),'archived_path':'architect-check.py','archived_sha256':H(archived),'normalization':'path tokens only; no second execution claimed'},'report':{'original_path':'<TMP>/vpkb-dependency-architect-review.json','raw_sha256':H(original.read_bytes()),'archived_path':'architect-review.json','archived_sha256':H(target.read_bytes()),'normalization':'byte-exact'},'external_inputs':'Only prior <TMP>/vpkb-dependency-source-review archives/metadata/source files and unchanged repo lock/vendor. No third-party source or archives added to this repository.','limits':['Source/license observations, not legal compliance or a human gate.','No exact PyPI Git provenance, transitive/model audit or parser/model execution.','Normalized script requires rebinding paths and original temporary artifacts; it is not a standalone installation instruction.']})
print('history evidence and appended dependency Architect index prepared')
