from pathlib import Path
import hashlib,json,datetime
root=Path('/Users/huangzhanpeng/python_code/video-paper-wiki'); d=root/'artifacts/verification/manual-pdf-v1/full-todo-v1/code-proof-v1/config-r1'
def ref(name):
 p=d/name; b=p.read_bytes(); return {'path':str(p.relative_to(root)),'size_bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
files=[ref(x) for x in ['static-vectors-r2.json','generate-static-vectors-r2.py','verify-static-vectors-r2.py','independent-verification-r2-py312.json','independent-verification-r2-py313.json','supplement-source-check-r2.json']]
r1=[ref(x) for x in ['static-vectors-r1.json','independent-verification-r1.json','fixture-review-r1.json']]
rec={'$schema':'video-paper-wiki.code-config-kernel-fixture-review-r2.v1','revision':2,'status':'READY_FOR_ARCHITECT_REVIEW_R2_NO_IMPLEMENTATION_ACCEPTANCE','recorded_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z'),'scope':'Bounded R2 correction of exact static value spans plus self-contained matrix/dynamic supplements; no production parser or test changes.','r1_rejection_bound':{'architect_review_path':'artifacts/verification/manual-pdf-v1/full-todo-v1/code-proof-v1/config-r1/architect-span-review-r1.json','architect_review_sha256':'7f9e5878df1b8b6050dd235c27db95bb66c1b38242e6155c7a32625523aa8474','r1_fixture_sha256':'a835382c7924969ee1d1b12b26e38fae126cc3ee03770ecfc23937b1b5915b24','r1_files_immutable':True},'r2_fixture':{'path':'artifacts/verification/manual-pdf-v1/full-todo-v1/code-proof-v1/config-r1/static-vectors-r2.json','success_vectors':7,'refusal_vectors':31,'value_spans_checked':50,'expected_nodes':61,'corrected_findings':7,'semantic_source_purpose_fields_preserved':True,'supplementary_groups':{'toml_transition_matrix':{'source_sha256':'18fc7340d6ceba4732c24b2c803fe0902732d6f3ed5dc4b761f90153c1c226bf','embedded_cases':26},'dynamic_offsets':{'source_sha256':'6a1d0215e994f0f4d4c559eb0c4e859944645899d78a6617372acc0dfbe470f8','embedded_vectors':9}}},'replay':{'py312':{'executable':'/private/tmp/l4r5.s54ypl35/locked-312/bin/python','version':'3.12.14','result':'PASS_R2_EXACT_VALUE_SPANS_AND_EMBEDDED_SUPPLEMENTS'},'py313':{'executable':'/Users/huangzhanpeng/python_code/video-paper-wiki/.venv/bin/python','version':'3.13.13','result':'PASS_R2_EXACT_VALUE_SPANS_AND_EMBEDDED_SUPPLEMENTS'},'checks':['all 50 nonnull value spans parse as exact complete stdlib values at their path','root container spans complete','value-span containment','array element source order','declaration token/path correspondence and coordinates','raw/codepoint/line/column/hash parity','self-contained embedded matrix and dynamic groups','manual critical span assertions']},'provenance':{'source_or_test_mutation':False,'git_mutation':False,'network_or_provider':False,'real_vault':False,'production_imported':False},'artifacts':files,'immutable_r1_artifacts':r1,'result':'R2_FIXTURE_CORRECTION_COMPLETE_PENDING_ARCHITECT_REVIEW'}
out=d/'fixture-review-r2.json';out.write_text(json.dumps(rec,ensure_ascii=False,indent=2)+'\n');print(out,len(out.read_bytes()),hashlib.sha256(out.read_bytes()).hexdigest())
